#######
# Compiled from data/x_seat/functions/disable.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/disable.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | disable
# Removes/disables nearly all of S.E.A.T pack from world but can still be re-enabled without reloading


data remove storage x_core flags.ticker__Packs[{x_SEAT:1}]
data remove storage x_core flags.trackSneakTime__Packs[{x_SEAT:1}]
data remove storage x_core flags.scrollBar__Packs[{x_SEAT:1}]
data remove storage x_core flags.blockCollisions__Packs[{x_SEAT:1}]
data remove storage x_core flags.attach__Packs[{x_SEAT:1}]
data remove storage x_core flags.monitorItems__Packs[{x_SEAT:1}]
scoreboard players reset * x_SEAT_ID
scoreboard players reset * x_SEAT_TICK
scoreboard players reset * x_SEAT_SCROLLED
tag @e remove x_MAY_SIT
tag @e remove x_MAY_SIT_SKIP
tag @e remove x_MAY_NOT_SIT
tag @e remove x_MAY_ADJUST_SEAT
tag @e remove x_MAY_ADJUST_SEAT_SKIP
tag @e remove x_ADJUSTING_SEAT
tag @e remove x_ADJUSTING_SEAT_SKIP
tag @e remove x_SEATED
tag @e remove x_SEAT_BLOCKING_INTERACTIONS    
tag @e remove x_SEAT_BASE_PLAYER
tag @e remove x_SEAT_SURFACE_PLAYER
tag @e remove x_SEAT_ANCHOR_PLAYER
tag @e remove x_SEAT_RIDE
tag @e remove x_SEAT_NO_RIDE
tag @e remove x_SEAT_ANCHOR_RIDE
tag @e remove x_SEAT_ANCHOR_RIDE_FROZEN
execute as @e[tag=x_EID__SEAT] at @s run scoreboard players remove @s x_EID__T 1
execute as @e[tag=x_EID__SEAT] at @s run tag @s remove x_EID__SEAT
execute as @e[tag=x_NO_COLLIDE__SEAT] at @s run scoreboard players remove @s x_NO_COLLIDE__T 1
execute as @e[tag=x_NO_COLLIDE__SEAT] at @s run tag @s remove x_NO_COLLIDE__SEAT
execute as @e[tag=x_ATTACH__SEAT] at @s run scoreboard players remove @s x_ATTACH__T 1
execute as @e[tag=x_ATTACH__SEAT] at @s run tag @s remove x_ATTACH__SEAT
execute as @e[tag=x_SCROLLBAR__SEAT] at @s run scoreboard players remove @s x_SCROLLBAR__T 1
execute as @e[tag=x_SCROLLBAR__SEAT] at @s run tag @s remove x_SCROLLBAR__SEAT
kill @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR]
kill @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR]
kill @e[tag=x_SEAT_NS,tag=x_SEAT_INTERACTION_BLOCKER]
kill @e[tag=x_SEAT_NS,tag=x_SEAT]
data modify storage x_seat flags.enabled set value 0