#######
# Compiled from data/x_seat/functions/kill_seat.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/kill_seat.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | kill_seat
# Disposes S.E.A.T entities


tag @s[tag=x_SEAT] add x_KILL_SEAT
tag @s[tag=x_SEAT_ANCHOR] add x_KILL_SEAT
tag @s[tag=x_SEAT_SENSOR] add x_KILL_SEAT
execute as @a[nbt={RootVehicle:{Entity:{Tags:[x_SEAT_NS,x_SEAT]}}}] at @s if score @s x_EID = @e[tag=x_KILL_SEAT,tag=x_SEAT_SURFACE,limit=1,sort=nearest] x_SEAT_ID run tp @s ~ ~1.5 ~
kill @e[tag=x_KILL_SEAT]