#######
# Compiled from data/x_seat/functions/main.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | main 
# Runs on every tick. About 20 times a second.


execute unless data storage x_core flags{reload:1} unless data storage x_core flags{reload:-1} if data storage x_core packs.x_core if data storage x_core packs{x_seat:116506} run function x_seat:runtime
execute unless data storage x_core flags{reload:1} unless data storage x_core flags{reload:-1} unless data storage x_core packs.x_core unless data storage x_core packs{x_seat:116506} run function x_seat:uninstall

