#######
# Compiled from data/x_seat/functions/runtime.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/runtime.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | runtime
# Performs runtime S.E.A.T tasks.
# Runs every tick.


function x_seat:player_interface
function x_seat:seat
execute if data storage x_seat flags{onlyIfSneaking:1} unless data storage x_core flags.trackSneakTime run data modify storage x_core flags merge value {trackSneakTime:1}
execute if data storage x_seat flags{onlyIfSneaking:1} unless data storage x_core flags.trackSneakTime__Packs[{x_SEAT:1}] run data modify storage x_core flags.trackSneakTime__Packs append value {x_SEAT:1}
execute unless data storage x_seat flags{onlyIfSneaking:1} if data storage x_core flags.trackSneakTime__Packs[{x_SEAT:1}] run data remove storage x_core flags.trackSneakTime__Packs[{x_SEAT:1}]
execute if entity @a[tag=x_SEATED] unless data storage x_core flags.scrollBar run data modify storage x_core flags merge value {scrollBar:1}
execute if entity @a[tag=x_SEATED] unless data storage x_core flags.scrollBar__Packs[{x_SEAT:1}] run data modify storage x_core flags.scrollBar__Packs append value {x_SEAT:1}
execute unless entity @a[tag=x_SEATED] if data storage x_core flags.scrollBar__Packs[{x_SEAT:1}] run data remove storage x_core flags.scrollBar__Packs[{x_SEAT:1}]
execute if entity @e[tag=x_SEAT_NS] unless data storage x_core flags.ticker run data modify storage x_core flags merge value {ticker:1}
execute if entity @e[tag=x_SEAT_NS] unless data storage x_core flags.ticker__Packs[{x_SEAT:1}] run data modify storage x_core flags.ticker__Packs append value {x_SEAT:1}
execute if entity @e[tag=x_SEAT_NS] unless data storage x_core flags.blockCollisions run data modify storage x_core flags merge value {blockCollisions:1}
execute if entity @e[tag=x_SEAT_NS] unless data storage x_core flags.blockCollisions__Packs[{x_SEAT:1}] run data modify storage x_core flags.blockCollisions__Packs append value {x_SEAT:1}
execute if entity @e[tag=x_SEAT_NS] unless data storage x_core flags.attach run data modify storage x_core flags merge value {attach:1}
execute if entity @e[tag=x_SEAT_NS] unless data storage x_core flags.attach__Packs[{x_SEAT:1}] run data modify storage x_core flags.attach__Packs append value {x_SEAT:1}
execute if entity @e[tag=x_SEAT_NS] unless data storage x_core flags.monitorItems run data modify storage x_core flags merge value {monitorItems:1}
execute if entity @e[tag=x_SEAT_NS] unless data storage x_core flags.monitorItems__Packs[{x_SEAT:1}] run data modify storage x_core flags.monitorItems__Packs append value {x_SEAT:1}
execute unless entity @e[tag=x_SEAT_NS] if data storage x_core flags.ticker__Packs[{x_SEAT:1}] run data remove storage x_core flags.ticker__Packs[{x_SEAT:1}]
execute unless entity @e[tag=x_SEAT_NS] if data storage x_core flags.blockCollisions__Packs[{x_SEAT:1}] run data remove storage x_core flags.blockCollisions__Packs[{x_SEAT:1}]
execute unless entity @e[tag=x_SEAT_NS] if data storage x_core flags.attach__Packs[{x_SEAT:1}] run data remove storage x_core flags.attach__Packs[{x_SEAT:1}]
execute unless entity @e[tag=x_SEAT_NS] if data storage x_core flags.monitorItems__Packs[{x_SEAT:1}] run data remove storage x_core flags.monitorItems__Packs[{x_SEAT:1}]
execute if data storage x_seat flags{rotationLock:1} run tag @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=x_ATTACH] add x_ATTACH_ROTATE
execute unless data storage x_seat flags{rotationLock:1} run tag @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR] remove x_ATTACH_ROTATE
tag @e[tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_MAY_SIT,tag=!x_MAY_SIT_SKIP,tag=!x_MAY_NOT_SIT,tag=!x_SCROLLBAR__SEAT,tag=!x_NO_COLLIDE__SEAT,tag=!x_MAY_ADJUST_SEAT,tag=!x_MAY_ADJUST_SEAT_SKIP,tag=!x_ADJUSTING_SEAT,tag=!x_ADJUSTING_SEAT_SKIP,tag=!x_SEATED,tag=!x_SEAT_RIDE,tag=!x_SEAT_RIDE_SKIP,tag=!x_SEAT_NO_RIDE,tag=!x_SEAT_BLOCKING_INTERACTIONS,tag=!x_SEAT_BASE_PLAYER,tag=!x_SEAT_SURFACE_PLAYER,tag=!x_SEAT_ANCHOR_PLAYER,tag=!x_SEAT_ANCHOR_RIDE,tag=!x_SEAT_ANCHOR_RIDE_FROZEN] remove x_SEAT_NS
execute if data storage x_core flags{loadNotified:1} run advancement grant @a only x_seat:pack_loaded
