#######
# Compiled from data/x_seat/functions/seat_anchor.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/seat_anchor.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | seat_anchor 
# Handles S.E.A.T anchor tasks


execute if data storage x_seat flags{rotationLock:0} run data modify entity @s Rotation[0] set from entity @a[tag=x_SEAT_ANCHOR_PLAYER,limit=1,sort=nearest] Rotation[0]

execute unless entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER,nbt={RootVehicle:{Entity:{Tags:[x_SEAT_NS,x_SEAT_OCCUPIED]}}}] unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_BASE] unless entity @s[tag=x_KILL_SEAT] run schedule function x_seat:kill_seat 2t
execute unless entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER,nbt={RootVehicle:{Entity:{Tags:[x_SEAT_NS,x_SEAT_OCCUPIED]}}}] unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_BASE] unless entity @s[tag=x_KILL_SEAT] run tag @s add x_KILL_SEAT

data modify entity @s {} merge value {Glowing:0}  
execute if block ^ ^ ^ minecraft:water unless entity @s[tag=x_SEAT_ANCHOR_SUBMERGED] run data modify entity @e[tag=x_SEAT_ANCHOR_BASE,limit=1,sort=nearest] {} merge value {NoAI:1}
execute if block ^ ^ ^ minecraft:water unless entity @s[tag=x_SEAT_ANCHOR_SUBMERGED] run tag @s add x_SEAT_ANCHOR_SUBMERGED
execute unless block ^ ^ ^ minecraft:water if entity @s[tag=x_SEAT_ANCHOR_SUBMERGED] run data modify entity @e[tag=x_SEAT_ANCHOR_BASE,limit=1,sort=nearest] {} merge value {NoAI:0}
execute unless block ^ ^ ^ minecraft:water if entity @s[tag=x_SEAT_ANCHOR_SUBMERGED] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,limit=1,sort=nearest] x_ATTACH_Y -190
execute unless block ^ ^ ^ minecraft:water if entity @s[tag=x_SEAT_ANCHOR_SUBMERGED] run tag @s remove x_SEAT_ANCHOR_SUBMERGED
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=6] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -180
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=5] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -170
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=4] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -160
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=3] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -150
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=2] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -140
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=1] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -110
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=0] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=8] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=9] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=10] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=11] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=12] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=13] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=14] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute as @s[tag=x_SEAT_ANCHOR_SUBMERGED] at @s if block ^ ^ ^ minecraft:water[level=15] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -90
execute if block ^ ^-1 ^ #minecraft:fences unless entity @s[tag=x_SEAT_ANCHOR_ON_FENCE] unless entity @s[tag=x_ATTACH] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -240
execute if block ^ ^-1 ^ #minecraft:fence_gates unless entity @s[tag=x_SEAT_ANCHOR_ON_FENCE] unless entity @s[tag=x_ATTACH] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -240
execute if block ^ ^-1 ^ #minecraft:fences unless entity @s[tag=x_SEAT_ANCHOR_ON_FENCE] unless entity @s[tag=x_ATTACH] run tag @s add x_SEAT_ANCHOR_ON_FENCE
execute if block ^ ^-1 ^ #minecraft:fence_gates unless entity @s[tag=x_SEAT_ANCHOR_ON_FENCE] unless entity @s[tag=x_ATTACH] run tag @s add x_SEAT_ANCHOR_ON_FENCE

execute if entity @s[tag=x_SEAT_ANCHOR_ON_FENCE] unless block ^ ^-1 ^ #minecraft:fences unless block ^ ^-1 ^ #minecraft:fence_gates run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -190
execute if entity @s[tag=x_SEAT_ANCHOR_ON_FENCE] unless block ^ ^-1 ^ #minecraft:fences unless block ^ ^-1 ^ #minecraft:fence_gates run tag @s remove x_SEAT_ANCHOR_ON_FENCE

execute if block ^ ^-1 ^ #minecraft:walls unless entity @s[tag=x_SEAT_ANCHOR_ON_WALL] unless entity @s[tag=x_ATTACH] run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -250
execute if block ^ ^-1 ^ #minecraft:walls unless entity @s[tag=x_SEAT_ANCHOR_ON_WALL] unless entity @s[tag=x_ATTACH] run tag @s add x_SEAT_ANCHOR_ON_WALL

execute if entity @s[tag=x_SEAT_ANCHOR_ON_WALL] unless block ^ ^-1 ^ #minecraft:walls run scoreboard players set @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] x_ATTACH_Y -190
execute if entity @s[tag=x_SEAT_ANCHOR_ON_WALL] unless block ^ ^-1 ^ #minecraft:walls run tag @s remove x_SEAT_ANCHOR_ON_WALL

execute if data storage x_seat flags{fallDamage:1} store result score @s x_R0 run data get entity @s FallDistance 1
execute unless data storage x_seat flags{fallDamage:1} run scoreboard players set @s x_R0 0
execute if score @s x_R0 matches 3.. unless entity @s[tag=x_ATTACH] if data storage x_seat flags{physics:1} run data modify entity @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] {} merge value {NoAI:0}  
execute if score @s x_R0 matches 3.. unless entity @s[tag=x_ATTACH] run data modify entity @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] Motion set from entity @s Motion 
execute if score @s x_R0 matches 3.. unless entity @s[tag=x_ATTACH] run data modify entity @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] FallDistance set from entity @s FallDistance 
execute if score @s x_R0 matches 3.. unless entity @s[tag=x_ATTACH] run tag @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] add x_SEAT_FALLING
execute if score @s x_R0 matches 3.. unless entity @s[tag=x_ATTACH] run tag @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] remove x_SEAT_ANCHORED
execute if score @s x_R0 matches 3.. unless entity @s[tag=x_ATTACH] run tag @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] remove x_ATTACH
execute if score @s x_R0 matches 3.. unless entity @s[tag=x_ATTACH] run tag @e[tag=x_SEAT_ANCHOR_BASE,sort=nearest,limit=1] remove x_ATTACH_ROTATE

execute if entity @s[tag=x_ATTACH] unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_RIDE] run tag @s remove x_ATTACH_ROTATE
execute if entity @s[tag=x_ATTACH] unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_RIDE] run tag @s remove x_ATTACH

execute if entity @s[tag=x_ATTACH,tag=x_SEAT_ANCHOR_ADJUSTING] if data storage x_seat flags{freezeRideOnAdjust:1} as @e[tag=x_SEAT_ANCHOR_RIDE,sort=nearest,limit=1] at @s if entity @s[nbt=!{NoAI:1}] run tag @s add x_SEAT_ANCHOR_RIDE_FROZEN
execute if entity @s[tag=x_ATTACH,tag=x_SEAT_ANCHOR_ADJUSTING] if data storage x_seat flags{freezeRideOnAdjust:1} as @e[tag=x_SEAT_ANCHOR_RIDE,sort=nearest,limit=1] at @s if entity @s[nbt=!{NoAI:1}] run data merge entity @s {NoAI:1} 

execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] run tag @a[tag=x_SEAT_ANCHOR_PLAYER,limit=1,sort=nearest] add x_SEAT_NO_RIDE
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] unless score @s x_EID matches 1.. run function x_core:assign_eid
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s run tag @s add x_SEAT_NS
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s run tag @s add x_SEAT_RIDE
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s unless entity @s[tag=x_NO_COLLIDE] run tag @s add x_NO_COLLIDE__SEAT
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s run scoreboard players add @s x_NO_COLLIDE__T 1
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s run tag @s add x_NO_COLLIDE
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s unless score @s x_EID matches 1.. run tag @s add x_EID__SEAT
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s unless score @s x_EID matches 1.. run scoreboard players add @s x_EID__T 1
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s unless score @s x_EID matches 1.. run tag @s add x_EID
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] as @e[type=!#x_seat:non_rideables,tag=!x_SEAT_NO_RIDE,dy=-0.5,limit=1,sort=nearest] at @s unless score @s x_EID matches 1.. run function x_core:assign_eid
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run data modify entity @s Marker set value 1
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run scoreboard players reset @s x_TICK
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run tag @s add x_ATTACH_NEW_SECONDARY
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run tag @e[tag=x_SEAT_RIDE,limit=1,sort=nearest] add x_ATTACH_NEW_PRIMARY
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run function x_core:create_attachment
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run scoreboard players add @s x_ATTACH__T 1
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] if entity @s[tag=!x_ATTACH] if entity @e[dy=-0.5,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run tag @s add x_ATTACH
execute if entity @a[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_PLAYER] run tag @a[tag=x_SEAT_ANCHOR_PLAYER,limit=1,sort=nearest] remove x_SEAT_NO_RIDE

execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if score @s x_TICK matches 10 if data storage x_seat flags{physics:1} unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=x_SEAT_UNLINKED,distance=..1] run summon minecraft:fox ^ ^999 ^ {Tags:[x_SYSTEM,x_SEAT_NS,x_SEAT_UNLINKED,x_SEAT_SENSOR,x_SEAT_NO_RIDE,x_NO_COLLIDE,x_KILL_ON_UNINSTALL],CustomName:"[\"\",{\"text\":\"S.E.A.T SENSOR\"}]",ActiveEffects:[{Id:14,Duration:2147483647 ,ShowParticles:0b,Ambient:1b}],Health:0.1,Silent:1,Invulnerable:1,DeathLootTable:"minecraft:empty", Age:-2147483648, Sleeping:1, DeathTime:10, ForcedAge:-2147483648, InLove:0, Attributes:[{Name:"generic.movement_speed",Base:-1000}]}     
execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if score @s x_TICK matches 10 if data storage x_seat flags{physics:1} run tp @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=x_SEAT_UNLINKED,tag=!x_TP_KILL,sort=nearest,limit=1] ^ ^ ^
execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if score @s x_TICK matches 10 if data storage x_seat flags{physics:1} run scoreboard players operation @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=x_SEAT_UNLINKED,tag=!x_TP_KILL,sort=nearest,limit=1] x_SEAT_ID = @s x_SEAT_ID
execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if score @s x_TICK matches 10 if data storage x_seat flags{physics:1} run scoreboard players set @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=x_SEAT_UNLINKED,tag=!x_TP_KILL,sort=nearest,limit=1] x_TICK 0
execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if score @s x_TICK matches 10 if data storage x_seat flags{physics:1} run tag @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=x_SEAT_UNLINKED,tag=!x_TP_KILL,sort=nearest,limit=1] remove x_SEAT_UNLINKED

execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_SENSOR,distance=..0.15] if entity @s[tag=x_SEAT_ANCHOR_MOVING] run data modify entity @s Marker set value 1
execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_SENSOR,distance=..0.15] if entity @s[tag=x_SEAT_ANCHOR_MOVING] run tag @s remove x_SEAT_ANCHOR_MOVING
execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_SENSOR,distance=..0.15] run scoreboard players set @s x_TICK 20

execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if score @s x_TICK matches 20.. unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_SENSOR,distance=..0.15] unless entity @s[tag=x_SEAT_ANCHOR_MOVING] if data storage x_seat flags{physics:1} run data modify entity @s Marker set value 0
execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if score @s x_TICK matches 20.. unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_SENSOR,distance=..0.15] unless entity @s[tag=x_SEAT_ANCHOR_MOVING] run tag @s add x_SEAT_ANCHOR_MOVING    
execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] if score @s x_TICK matches 20.. unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR_SENSOR,distance=..0.15] run scoreboard players set @s x_TICK 0

execute if entity @s[tag=!x_ATTACH,tag=!x_SEAT_ANCHOR_ADJUSTING] unless score @s x_TICK matches 0.. run scoreboard players set @s x_TICK 1
