#######
# Compiled from data/x_seat/functions/seat_ride.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/seat_ride.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | seat_ride
# Handles S.E.A.T ride tasks


execute if entity @s[tag=x_SEAT_ANCHOR_RIDE_FROZEN] unless entity @e[tag=x_SEAT_RIDE_ANCHOR, tag=x_SEAT_ANCHOR_ADJUSTING] run data merge entity @s {NoAI:0}
execute if entity @s[tag=x_SEAT_ANCHOR_RIDE_FROZEN] if data storage x_seat flags{freezeRideOnAdjust:0} run data merge entity @s {NoAI:0}
execute if entity @s[tag=x_SEAT_ANCHOR_RIDE_FROZEN] unless entity @e[tag=x_SEAT_RIDE_ANCHOR, tag=x_SEAT_ANCHOR_ADJUSTING] run tag @s remove x_SEAT_ANCHOR_RIDE_FROZEN
execute if entity @s[tag=x_SEAT_ANCHOR_RIDE_FROZEN] if data storage x_seat flags{freezeRideOnAdjust:0} run tag @s remove x_SEAT_ANCHOR_RIDE_FROZEN

execute unless entity @e[tag=x_SEAT_RIDE_ANCHOR] if entity @s[tag=x_NO_COLLIDE__SEAT] run scoreboard players remove @s x_NO_COLLIDE__T 1
execute unless entity @e[tag=x_SEAT_RIDE_ANCHOR] if entity @s[tag=x_NO_COLLIDE__SEAT] run tag @s remove x_NO_COLLIDE__SEAT
execute unless entity @e[tag=x_SEAT_RIDE_ANCHOR] if entity @s[tag=x_EID__SEAT] run scoreboard players remove @s x_EID__T 1
execute unless entity @e[tag=x_SEAT_RIDE_ANCHOR] if entity @s[tag=x_EID__SEAT] run tag @s remove x_EID__SEAT
execute unless entity @e[tag=x_SEAT_RIDE_ANCHOR] run tag @s remove x_SEAT_ANCHOR_RIDE
execute unless entity @e[tag=x_SEAT_RIDE_ANCHOR] run tag @s remove x_SEAT_RIDE_SKIP
execute unless entity @e[tag=x_SEAT_RIDE_ANCHOR] run tag @s remove x_SEAT_RIDE
