#######
# Compiled from data/x_seat/functions/seat_base.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/seat_base.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | seat_base
# Handles S.E.A.T base tasks


execute if data storage x_seat flags{onlySitDown:0} run tag @s remove x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN

execute if data storage x_seat flags{onlySitDown:1} if entity @e[tag=x_SEAT_BASE_PLAYER,tag=!x_SEAT_ENABLED_FORCE_SIT_DOWN,limit=1,sort=nearest] run tag @s remove x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN

execute if data storage x_seat flags{onlySitDown:1} if entity @e[tag=x_SEAT_BASE_PLAYER,tag=x_SEAT_ENABLED_FORCE_SIT_DOWN,limit=1,sort=nearest] run tag @s add x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN

execute if data storage x_seat flags{onlySitDown:2} run tag @s add x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN

execute if data storage x_seat flags{physics:0} run tag @s add x_SEAT_BASE_DISABLED_PHYSICS

execute if data storage x_seat flags{physics:1} if entity @e[tag=x_SEAT_BASE_PLAYER,tag=!x_SEAT_DISABLED_PHYSICS,limit=1,sort=nearest] run tag @s remove x_SEAT_BASE_DISABLED_PHYSICS

execute if data storage x_seat flags{physics:1} if entity @e[tag=x_SEAT_BASE_PLAYER,tag=x_SEAT_DISABLED_PHYSICS,limit=1,sort=nearest] run tag @s add x_SEAT_BASE_DISABLED_PHYSICS

execute if data storage x_seat flags{physics:2} run tag @s remove x_SEAT_BASE_DISABLED_PHYSICS

execute if data storage x_seat flags{bounceOffFloor:0} run tag @s remove x_SEAT_BASE_ENABLED_FLOOR_BOUNCE

execute if data storage x_seat flags{bounceOffFloor:1} if entity @e[tag=x_SEAT_BASE_PLAYER,tag=!x_SEAT_ENABLED_FLOOR_BOUNCE,limit=1,sort=nearest] run tag @s remove x_SEAT_BASE_ENABLED_FLOOR_BOUNCE

execute if data storage x_seat flags{bounceOffFloor:1} if entity @e[tag=x_SEAT_BASE_PLAYER,tag=x_SEAT_ENABLED_FLOOR_BOUNCE,limit=1,sort=nearest] run tag @s add x_SEAT_BASE_ENABLED_FLOOR_BOUNCE

execute if data storage x_seat flags{bounceOffFloor:2} run tag @s add x_SEAT_BASE_ENABLED_FLOOR_BOUNCE

execute if score @s x_TICK matches 40.. unless entity @s[tag=x_KILL_SEAT] run schedule function x_seat:kill_seat 2t
execute if score @s x_TICK matches 40.. unless entity @s[tag=x_KILL_SEAT] run tag @s add x_KILL_SEAT

execute unless entity @s[tag=x_KILL_SEAT] unless entity @a[tag=x_SEAT_BASE_PLAYER] run schedule function x_seat:kill_seat 2t
execute unless entity @s[tag=x_KILL_SEAT] unless entity @a[tag=x_SEAT_BASE_PLAYER] run tag @s add x_KILL_SEAT
execute unless entity @s[tag=x_KILL_SEAT] unless entity @e[tag=x_SEAT_BASE_SURFACE] run schedule function x_seat:kill_seat 2t
execute unless entity @s[tag=x_KILL_SEAT] unless entity @e[tag=x_SEAT_BASE_SURFACE] run tag @s add x_KILL_SEAT
execute unless entity @s[tag=x_KILL_SEAT] if entity @s[nbt={Leash:{}}] run schedule function x_seat:kill_seat 2t
execute unless entity @s[tag=x_KILL_SEAT] if entity @s[nbt={Leash:{}}] run tag @s add x_KILL_SEAT

execute if entity @s[tag=!x_SEAT_BASE_DISABLED_PHYSICS] if entity @s[tag=x_SEAT_ANCHORED,tag=!x_SEAT_FALLING] unless entity @e[tag=x_SEAT_BASE_ANCHOR] unless entity @s[tag=x_KILL_SEAT] run schedule function x_seat:kill_seat 2t
execute if entity @s[tag=!x_SEAT_BASE_DISABLED_PHYSICS] if entity @s[tag=x_SEAT_ANCHORED,tag=!x_SEAT_FALLING] unless entity @e[tag=x_SEAT_BASE_ANCHOR] unless entity @s[tag=x_KILL_SEAT] run tag @s add x_KILL_SEAT

data modify entity @s Rotation[1] set value 0
data modify entity @s {} merge value {Sleeping:1,Glowing:0}    
execute if entity @s[tag=!x_SEAT_OCCUPIED] if entity @a[tag=x_SEAT_BASE_PLAYER,tag=!x_SEATED,nbt={RootVehicle: {Entity:{Tags:[x_SEAT_NS,x_SEAT_BASE]}}},nbt=!{RootVehicle: {Entity:{Tags:[x_SEAT_BASE_SKIP]}}}] run tag @s add x_SEAT_SEATING

execute if entity @s[tag=x_SEAT_SEATING] run tag @s remove x_KILL_SEAT     
execute if entity @s[tag=x_SEAT_SEATING] run tag @a[tag=x_SEAT_BASE_PLAYER,limit=1,sort=nearest] add x_SEAT_NS
execute if entity @s[tag=x_SEAT_SEATING] run tag @a[tag=x_SEAT_BASE_PLAYER,limit=1,sort=nearest] add x_SEATED
execute if entity @s[tag=x_SEAT_SEATING] run advancement grant @a[tag=x_SEAT_BASE_PLAYER,limit=1,sort=nearest] only x_seat:take_a_seat
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN] if block ^ ^1.9 ^-0.7 #x_core:non_solids run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_SIT_BACK
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN] if block ^ ^2.9 ^-0.7 #x_core:non_solids run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_SIT_BACK
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN] if block ^ ^1.9 ^-0.7 minecraft:snow run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_SIT_BACK
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN] if block ^ ^2.9 ^-0.7 minecraft:snow run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_SIT_BACK
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN] if block ^ ^1.9 ^-0.7 #x_core:non_solids run tag @s add x_SEAT_SIT_BACK
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN] if block ^ ^2.9 ^-0.7 #x_core:non_solids run tag @s add x_SEAT_SIT_BACK
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN] if block ^ ^1.9 ^-0.7 minecraft:snow run tag @s add x_SEAT_SIT_BACK
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_BASE_ENABLED_FORCE_SIT_DOWN] if block ^ ^2.9 ^-0.7 minecraft:snow run tag @s add x_SEAT_SIT_BACK
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] run tp @s ^ ^-0.5 ^-0.5
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s unless entity @s[tag=x_SEAT_SIT_BACK] run tp @s ^ ^-0.5 ^
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] unless block ^ ^3.9 ^-0.5 #x_core:non_solids unless block ^ ^3.9 ^-0.5 minecraft:snow run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_LOW_ROOF
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] unless block ^ ^3.9 ^-0.5 #x_core:non_solids unless block ^ ^3.9 ^-0.5 minecraft:snow run tag @s add x_SEAT_LOW_ROOF
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_SIT_BACK] unless block ^ ^3.9 ^ #x_core:non_solids unless block ^ ^3.9 ^ minecraft:snow run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_LOW_ROOF
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_SIT_BACK] unless block ^ ^3.9 ^ #x_core:non_solids unless block ^ ^3.9 ^ minecraft:snow run tag @s add x_SEAT_LOW_ROOF
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] if block ^ ^1.9 ^-0.5 #x_core:non_solids run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_ON_FLOOR
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] if block ^ ^1.9 ^-0.5 minecraft:snow run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_ON_FLOOR
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] if block ^ ^1.9 ^-0.5 #x_core:non_solids run tag @s add x_SEAT_ON_FLOOR
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] if block ^ ^1.9 ^-0.5 minecraft:snow run tag @s add x_SEAT_ON_FLOOR
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] if block ^ ^1.9 ^-0.5 #x_seat:half_height run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_HALF_HEIGHT
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_SIT_BACK] if block ^ ^1.9 ^-0.5 #x_seat:half_height run tag @s add x_SEAT_HALF_HEIGHT
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_SIT_BACK] if block ^ ^1.9 ^ #x_core:non_solids run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_ON_FLOOR
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_SIT_BACK] if block ^ ^1.9 ^ minecraft:snow run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_ON_FLOOR
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_SIT_BACK] if block ^ ^1.9 ^ #x_core:non_solids run tag @s add x_SEAT_ON_FLOOR
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_SIT_BACK] if block ^ ^1.9 ^ minecraft:snow run tag @s add x_SEAT_ON_FLOOR
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_SIT_BACK] if block ^ ^1.9 ^-0.5 #x_seat:half_height run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_HALF_HEIGHT
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_SIT_BACK] if block ^ ^1.9 ^-0.5 #x_seat:half_height run tag @s add x_SEAT_HALF_HEIGHT
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_LOW_ROOF,tag=!x_SEAT_ON_FLOOR] run tp @s ^ ^0.8 ^
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_HALF_HEIGHT] run tp @s ^ ^0.6 ^
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_ON_FLOOR,tag=!x_SEAT_HALF_HEIGHT] run tp @s ^ ^1 ^
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s unless block ^ ^1.9 ^-0.6 #x_core:non_solids unless block ^ ^1.9 ^-0.6 #x_core:semi_solids unless block ^ ^1.9 ^-0.6 minecraft:snow run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_TOO_CLOSE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s unless block ^ ^1.9 ^-0.6 #x_core:non_solids unless block ^ ^1.9 ^-0.6 #x_core:semi_solids unless block ^ ^1.9 ^-0.6 minecraft:snow run tag @s add x_SEAT_TOO_CLOSE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_TOO_CLOSE] run tp @s ^ ^ ^0.3
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_TOO_CLOSE] if block ^ ^1.4 ^ #minecraft:fences run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_ON_FENCE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_TOO_CLOSE] if block ^ ^1.4 ^ #minecraft:fence_gates run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_ON_FENCE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_TOO_CLOSE] if block ^ ^1.4 ^ #minecraft:walls run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_ON_FENCE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_TOO_CLOSE] if block ^ ^1.4 ^ #minecraft:fences run tag @s add x_SEAT_ON_FENCE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_TOO_CLOSE] if block ^ ^1.4 ^ #minecraft:fence_gates run tag @s add x_SEAT_ON_FENCE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_TOO_CLOSE] if block ^ ^1.4 ^ #minecraft:walls run tag @s add x_SEAT_ON_FENCE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_ON_FENCE] run tp @s ^ ^0.5 ^
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s run tag @a[tag=x_SEAT_BASE_PLAYER,limit=1,sort=nearest] add x_SEAT_NO_RIDE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s positioned ^ ^ ^-0.5 if entity @s[tag=x_SEAT_SIT_BACK,tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_ON_FENCE,tag=x_SEAT_ON_FLOOR] if entity @e[dy=2.9,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_ON_RIDE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s positioned ^ ^ ^-0.5 if entity @s[tag=x_SEAT_SIT_BACK,tag=!x_SEAT_LOW_ROOF,tag=!x_SEAT_ON_FENCE,tag=x_SEAT_ON_FLOOR] if entity @e[dy=2.9,tag=!x_SEAT,tag=!x_SEAT_ANCHOR,tag=!x_SEAT_SENSOR,tag=!x_SEAT_NO_RIDE,type=!#x_seat:non_rideables] run tag @s add x_SEAT_ON_RIDE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=x_SEAT_ON_RIDE] run tp @s ^ ^1 ^
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_ANCHORED] run function x_seat:create_anchor
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_ANCHORED] run tag @s add x_ATTACH
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_ANCHORED] run tag @s add x_ATTACH_ROTATE
execute if entity @s[tag=x_SEAT_SEATING] positioned as @s if entity @s[tag=!x_SEAT_ANCHORED] run tag @s add x_SEAT_ANCHORED
execute if entity @s[tag=x_SEAT_SEATING] run tag @s add x_SEAT_OCCUPIED
execute if entity @s[tag=x_SEAT_SEATING] run scoreboard players reset @s x_TICK
execute if entity @s[tag=x_SEAT_SEATING] run tag @e[tag=x_SEAT_BASE_SURFACE,limit=1,sort=nearest] add x_SEAT_OCCUPIED
execute if entity @s[tag=x_SEAT_SEATING] run tag @a[tag=x_SEAT_BASE_PLAYER,limit=1,sort=nearest] remove x_SEAT_NO_RIDE
execute if entity @s[tag=x_SEAT_SEATING] run tag @s remove x_SEAT_SEATING

execute if entity @s[tag=x_SEAT_OCCUPIED] unless entity @a[tag=x_SEAT_BASE_PLAYER,nbt={RootVehicle:{Entity:{Tags:[x_SEAT_NS,x_SEAT_OCCUPIED,x_SEAT_BASE]}}},nbt=!{RootVehicle:{Entity:{Tags:[x_SEAT_BASE_SKIP]}}}] unless entity @s[tag=x_KILL_SEAT] run schedule function x_seat:kill_seat 2t
execute if entity @s[tag=x_SEAT_OCCUPIED] unless entity @a[tag=x_SEAT_BASE_PLAYER,nbt={RootVehicle:{Entity:{Tags:[x_SEAT_NS,x_SEAT_OCCUPIED,x_SEAT_BASE]}}},nbt=!{RootVehicle:{Entity:{Tags:[x_SEAT_BASE_SKIP]}}}] unless entity @s[tag=x_KILL_SEAT] run tag @s add x_KILL_SEAT
execute if entity @s[tag=x_SEAT_OCCUPIED] if entity @s[tag=x_SEAT_BASE_DISABLED_PHYSICS] run function x_seat:seat_physics
