#######
# Compiled from data/x_seat/functions/seat_sensor.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/seat_sensor.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | seat_sensor
# Handles S.E.A.T physics sensor tasks


data modify entity @s Rotation[0] set from entity @a[tag=x_SEAT_ANCHOR_PLAYER,limit=1,sort=nearest] Rotation[0]
execute unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR_ANCHOR] run function x_seat:kill_seat

data modify entity @s {} merge value {Sleeping:1,Glowing:0}
execute if score @s x_TICK matches 30.. unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR_ANCHOR,tag=!x_SEAT_ANCHOR_MOVING,distance=..0.15] run function x_seat:kill_seat
execute if score @s x_TICK matches 30.. run scoreboard players set @s x_TICK 0
