#######
# Compiled from data/x_seat/functions/seat.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/seat.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | seat 
# Handles general S.E.A.T routines


execute as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] at @s as @a at @s if score @s x_EID = @e[tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_BASE_PLAYER
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] at @s as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR] at @s if score @s x_SEAT_ID = @e[tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_BASE_ANCHOR
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] at @s as @e[tag=x_SEAT_SURFACE] at @s if score @s x_SEAT_ID = @e[tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_BASE_SURFACE
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] at @s run function x_seat:seat_base
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] at @s run tag @a remove x_SEAT_BASE_PLAYER
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] at @s run tag @e remove x_SEAT_BASE_ANCHOR
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] at @s run tag @e remove x_SEAT_BASE_SURFACE
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP,limit=1] at @s run tag @s add x_SEAT_BASE_SKIP
execute unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_BASE,tag=!x_SEAT_BASE_SKIP] run tag @e remove x_SEAT_BASE_SKIP

execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP,limit=1] at @s as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE] at @s if score @s x_SEAT_ID = @e[tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_SURFACE_BASE
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP,limit=1] at @s as @a at @s if score @s x_EID = @e[tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_SURFACE_PLAYER
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP,limit=1] at @s run function x_seat:seat_surface
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP,limit=1] at @s run tag @a remove x_SEAT_SURFACE_PLAYER
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP,limit=1] at @s run tag @e remove x_SEAT_SURFACE_BASE
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP,limit=1] at @s run tag @s add x_SEAT_SURFACE_SKIP
execute unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_SURFACE,tag=!x_SEAT_SURFACE_SKIP] run tag @e remove x_SEAT_SURFACE_SKIP

execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s as @e[tag=x_SEAT_NS,tag=x_SEAT_BASE] at @s if score @s x_SEAT_ID = @e[tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_ANCHOR_BASE
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s as @a at @s if score @s x_EID = @e[tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_ANCHOR_PLAYER
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s as @e[tag=x_SEAT_NS,tag=x_SEAT_RIDE] at @s if score @s x_EID = @e[tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] x_PID run tag @s add x_SEAT_ANCHOR_RIDE
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s as @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR] at @s if score @s x_SEAT_ID = @e[tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_ANCHOR_SENSOR
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s run function x_seat:seat_anchor
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s run tag @e remove x_SEAT_ANCHOR_BASE
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s run tag @a remove x_SEAT_ANCHOR_PLAYER
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s run tag @a remove x_SEAT_ANCHOR_RIDE
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s run tag @a remove x_SEAT_ANCHOR_SENSOR
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP,limit=1] at @s run tag @s add x_SEAT_ANCHOR_SKIP
execute unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=!x_SEAT_ANCHOR_SKIP] run tag @e remove x_SEAT_ANCHOR_SKIP

execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=!x_SEAT_SENSOR_SKIP,limit=1] at @s as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR] at @s if score @s x_SEAT_ID = @e[tag=x_SEAT_SENSOR,tag=!x_SEAT_SENSOR_SKIP,limit=1] x_SEAT_ID run tag @s add x_SEAT_SENSOR_ANCHOR
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=!x_SEAT_SENSOR_SKIP,limit=1] at @s run function x_seat:seat_sensor
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=!x_SEAT_SENSOR_SKIP,limit=1] at @s run tag @e remove x_SEAT_SENSOR_ANCHOR
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=!x_SEAT_SENSOR_SKIP,limit=1] at @s run tag @s add x_SEAT_SENSOR_SKIP
execute unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR,tag=!x_SEAT_SENSOR_SKIP] run tag @e remove x_SEAT_SENSOR_SKIP

execute as @e[tag=x_SEAT_NS,tag=x_SEAT_RIDE,tag=!x_SEAT_RIDE_SKIP,limit=1] at @s as @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR,tag=x_ATTACH] at @s if score @s x_PID = @e[tag=x_SEAT_RIDE,tag=!x_SEAT_RIDE_SKIP,limit=1] x_EID run tag @s add x_SEAT_RIDE_ANCHOR
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_RIDE,tag=!x_SEAT_RIDE_SKIP,limit=1] at @s run function x_seat:seat_ride
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_RIDE,tag=!x_SEAT_RIDE_SKIP,limit=1] at @s run tag @e remove x_SEAT_RIDE_ANCHOR
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_RIDE,tag=!x_SEAT_RIDE_SKIP,limit=1] at @s run tag @s add x_SEAT_RIDE_SKIP
execute unless entity @e[tag=x_SEAT_NS,tag=x_SEAT_RIDE,tag=!x_SEAT_RIDE_SKIP] run tag @e remove x_SEAT_RIDE_SKIP

execute as @e[tag=x_SEAT_NS,tag=x_SEAT_NO_RIDE] at @s unless entity @e[distance=..7,tag=x_SEAT_ANCHOR,tag=x_ATTACH] unless entity @s[tag=x_SEAT] unless entity @s[tag=x_SEAT_ANCHOR] unless entity @s[tag=x_SEAT_SENSOR] unless entity @s[tag=x_SEAT_INTERACTION_BLOCKER] run tag @s remove x_SEAT_NO_RIDE
execute as @a[tag=x_SEAT_NS,tag=x_SEAT_BLOCKING_INTERACTIONS] at @s unless entity @e[distance=..7,tag=x_SEAT_INTERACTION_BLOCKER] run summon minecraft:armor_stand ~ ~ ~ {Tags:[x_SEAT_NS,x_SEAT_INTERACTION_BLOCKER,x_SEAT_NO_RIDE,x_NO_COLLIDE,x_KILL_ON_UNINSTALL],Invisible:1,NoGravity:1,Small:0,Invulnerable:1}
execute as @a[tag=x_SEAT_NS,tag=x_SEAT_BLOCKING_INTERACTIONS] at @s unless entity @s[nbt={SelectedItem:{id:"minecraft:sweet_berries"}}] unless entity @s[nbt={SelectedItem:{id:"minecraft:wheat"}}] unless entity @s[nbt={SelectedItem:{id:"minecraft:hay_bale"}}] unless entity @s[nbt={SelectedItem:{id:"minecraft:lead"}}] run tag @s remove x_SEAT_BLOCKING_INTERACTIONS     
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_INTERACTION_BLOCKER] at @s run tp @s @a[distance=..7,tag=x_SEAT_NS,tag=x_SEAT_BLOCKING_INTERACTIONS,limit=1,sort=nearest]
execute as @e[tag=x_SEAT_NS,tag=x_SEAT_INTERACTION_BLOCKER] at @s unless entity @e[distance=..7,tag=x_SEAT_NS,tag=x_SEAT_BLOCKING_INTERACTIONS] run kill @s
tag @a[tag=x_SEAT_NS, tag=x_SEAT_BLOCKING_INTERACTIONS, nbt=!{RootVehicle:{Entity:{Tags:[x_SEAT_NS,x_SEAT_OCCUPIED]}}}] remove x_SEAT_BLOCKING_INTERACTIONS