#######
# Compiled from data/x_seat/functions/ui.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/ui.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | ui
# Handles user interface


execute as @a[scores={S.E.A.T=1..99}] at @s if score @s S.E.A.T matches 11 run tag @s add x_SEAT_PLAYER_DISABLED
execute as @a[scores={S.E.A.T=1..99}] at @s if score @s S.E.A.T matches 12 run tag @s remove x_SEAT_PLAYER_DISABLED
execute as @a[scores={S.E.A.T=1..99}] at @s run scoreboard players set @s S.E.A.T 100
execute as @a[scores={S.E.A.T=101..199}] at @s if score @s S.E.A.T matches 111 run tag @s add x_SEAT_DISABLED_PHYSICS
execute as @a[scores={S.E.A.T=101..199}] at @s if score @s S.E.A.T matches 112 run tag @s remove x_SEAT_DISABLED_PHYSICS
execute as @a[scores={S.E.A.T=101..199}] at @s if score @s S.E.A.T matches 121 run tag @s remove x_SEAT_ENABLED_ROTATION_LOCK
execute as @a[scores={S.E.A.T=101..199}] at @s if score @s S.E.A.T matches 122 run tag @s add x_SEAT_ENABLED_ROTATION_LOCK
execute as @a[scores={S.E.A.T=101..199}] at @s if score @s S.E.A.T matches 131 run tag @s remove x_SEAT_ENABLED_FORCE_SNEAKING
execute as @a[scores={S.E.A.T=101..199}] at @s if score @s S.E.A.T matches 132 run tag @s add x_SEAT_ENABLED_FORCE_SNEAKING
execute as @a[scores={S.E.A.T=101..199}] at @s run scoreboard players set @s S.E.A.T 100
execute as @a[scores={S.E.A.T=201..299}] at @s if score @s S.E.A.T matches 211 run tag @s remove x_SEAT_ENABLED_FLOOR_BOUNCE
execute as @a[scores={S.E.A.T=201..299}] at @s if score @s S.E.A.T matches 212 run tag @s add x_SEAT_ENABLED_FLOOR_BOUNCE
execute as @a[scores={S.E.A.T=201..299}] at @s if score @s S.E.A.T matches 221 run tag @s remove x_SEAT_ENABLED_FORCE_SIT_DOWN
execute as @a[scores={S.E.A.T=201..299}] at @s if score @s S.E.A.T matches 222 run tag @s add x_SEAT_ENABLED_FORCE_SIT_DOWN
execute as @a[scores={S.E.A.T=201..299}] at @s if score @s S.E.A.T matches 231 run tag @s add x_SEAT_DISABLED_FREEZE_RIDE
execute as @a[scores={S.E.A.T=201..299}] at @s if score @s S.E.A.T matches 232 run tag @s remove x_SEAT_DISABLED_FREEZE_RIDE
execute as @a[scores={S.E.A.T=201..299}] at @s run scoreboard players set @s S.E.A.T 200
execute as @a[scores={S.E.A.T=301..399}] at @s if score @s S.E.A.T matches 311 run tag @s add x_SEAT_DISABLED_ADJUSTMENT
execute as @a[scores={S.E.A.T=301..399}] at @s if score @s S.E.A.T matches 312 run tag @s remove x_SEAT_DISABLED_ADJUSTMENT
execute as @a[scores={S.E.A.T=301..399}] at @s if score @s S.E.A.T matches 321 run tag @s add x_SEAT_DISABLED_ON_MOBS
execute as @a[scores={S.E.A.T=301..399}] at @s if score @s S.E.A.T matches 322 run tag @s remove x_SEAT_DISABLED_ON_MOBS
execute as @a[scores={S.E.A.T=301..399}] at @s if score @s S.E.A.T matches 331 run tag @s add x_SEAT_DISABLED_ADJUSTMENT_LIMITS
execute as @a[scores={S.E.A.T=301..399}] at @s if score @s S.E.A.T matches 332 run tag @s remove x_SEAT_DISABLED_ADJUSTMENT_LIMITS
execute as @a[scores={S.E.A.T=301..399}] at @s run scoreboard players set @s S.E.A.T 300
execute as @a[scores={S.E.A.T=401..499}] at @s if score @s S.E.A.T matches 411 run tag @s add x_SEAT_DISABLED_FALL_DAMAGE
execute as @a[scores={S.E.A.T=401..499}] at @s if score @s S.E.A.T matches 412 run tag @s remove x_SEAT_DISABLED_FALL_DAMAGE
execute as @a[scores={S.E.A.T=401..499}] at @s if score @s S.E.A.T matches 421 run tag @s add x_SEAT_DISABLED_INVENTORY_BLOCK
execute as @a[scores={S.E.A.T=401..499}] at @s if score @s S.E.A.T matches 422 run tag @s remove x_SEAT_DISABLED_INVENTORY_BLOCK
execute as @a[scores={S.E.A.T=401..499}] at @s if score @s S.E.A.T matches 431 run tag @s add x_SEAT_DISABLED_PROMPTS
execute as @a[scores={S.E.A.T=401..499}] at @s if score @s S.E.A.T matches 432 run tag @s remove x_SEAT_DISABLED_PROMPTS
execute as @a[scores={S.E.A.T=401..499}] at @s run scoreboard players set @s S.E.A.T 400
execute as @a[scores={S.E.A.T=1..499}] at @s run tellraw @s "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
execute as @a[scores={S.E.A.T=1..499}] at @s run function x_seat:player_menu
execute as @a[scores={S.E.A.T=1..499}] at @s run scoreboard players reset @s S.E.A.T
execute as @a[scores={S.E.A.T=1..}] at @s run tellraw @s "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
execute as @a[scores={S.E.A.T=1..}] at @s run function x_seat:player_menu
execute as @a[scores={S.E.A.T=1..}] at @s run scoreboard players reset @s S.E.A.T
execute as @a[scores={S.E.A.T=500}] at @s run tellraw @s "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
execute as @a[scores={S.E.A.T=500}] at @s run scoreboard players reset @s S.E.A.T
execute as @a[scores={x_SEAT_MENU=1..99}] at @s if score @s x_SEAT_MENU matches 11 run data modify storage x_seat flags.enabled set value 0
execute as @a[scores={x_SEAT_MENU=1..99}] at @s if score @s x_SEAT_MENU matches 12 run data modify storage x_seat flags.enabled set value 1
execute as @a[scores={x_SEAT_MENU=1..99}] at @s if score @s x_SEAT_MENU matches 21 run function x_seat:uninstall
execute as @a[scores={x_SEAT_MENU=1..99}] at @s run scoreboard players set @s x_SEAT_MENU 100
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 111 run data modify storage x_seat flags.physics set value 1
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 112 run data modify storage x_seat flags.physics set value 0
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 113 run data modify storage x_seat flags.physics set value 2
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 121 run data modify storage x_seat flags.rotationLock set value 1
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 122 run data modify storage x_seat flags.rotationLock set value 0
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 123 run data modify storage x_seat flags.rotationLock set value 2
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 131 run data modify storage x_seat flags.onlyIfSneaking set value 1
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 132 run data modify storage x_seat flags.onlyIfSneaking set value 0
execute as @a[scores={x_SEAT_MENU=101..199}] at @s if score @s x_SEAT_MENU matches 133 run data modify storage x_seat flags.onlyIfSneaking set value 2
execute as @a[scores={x_SEAT_MENU=101..199}] at @s run scoreboard players set @s x_SEAT_MENU 100
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 211 run data modify storage x_seat flags.bounceOffFloor set value 1
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 212 run data modify storage x_seat flags.bounceOffFloor set value 0
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 213 run data modify storage x_seat flags.bounceOffFloor set value 2
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 221 run data modify storage x_seat flags.onlySitDown set value 1
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 222 run data modify storage x_seat flags.onlySitDown set value 0
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 223 run data modify storage x_seat flags.onlySitDown set value 2
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 231 run data modify storage x_seat flags.freezeRideOnAdjust set value 1
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 232 run data modify storage x_seat flags.freezeRideOnAdjust set value 0
execute as @a[scores={x_SEAT_MENU=201..299}] at @s if score @s x_SEAT_MENU matches 233 run data modify storage x_seat flags.freezeRideOnAdjust set value 2
execute as @a[scores={x_SEAT_MENU=201..299}] at @s run scoreboard players set @s x_SEAT_MENU 200
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 311 run data modify storage x_seat flags.seatAdjustment set value 1
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 312 run data modify storage x_seat flags.seatAdjustment set value 0
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 313 run data modify storage x_seat flags.seatAdjustment set value 2
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 321 run data modify storage x_seat flags.sitOnMobs set value 1
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 322 run data modify storage x_seat flags.sitOnMobs set value 0
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 323 run data modify storage x_seat flags.sitOnMobs set value 2
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 331 run data modify storage x_seat flags.adjustmentLimits set value 1
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 332 run data modify storage x_seat flags.adjustmentLimits set value 0
execute as @a[scores={x_SEAT_MENU=301..399}] at @s if score @s x_SEAT_MENU matches 333 run data modify storage x_seat flags.adjustmentLimits set value 2
execute as @a[scores={x_SEAT_MENU=301..399}] at @s run scoreboard players set @s x_SEAT_MENU 300
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 411 run data modify storage x_seat flags.fallDamage set value 1
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 412 run data modify storage x_seat flags.fallDamage set value 0
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 413 run data modify storage x_seat flags.fallDamage set value 2
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 421 run data modify storage x_seat flags.blockInventory set value 1
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 422 run data modify storage x_seat flags.blockInventory set value 0
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 423 run data modify storage x_seat flags.blockInventory set value 2
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 431 run data modify storage x_seat flags.showPrompts set value 1
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 432 run data modify storage x_seat flags.showPrompts set value 0
execute as @a[scores={x_SEAT_MENU=401..499}] at @s if score @s x_SEAT_MENU matches 433 run data modify storage x_seat flags.showPrompts set value 2
execute as @a[scores={x_SEAT_MENU=401..499}] at @s run scoreboard players set @s x_SEAT_MENU 400
execute as @a[scores={x_SEAT_MENU=1..499}] at @s run tellraw @s "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
execute as @a[scores={x_SEAT_MENU=1..499}] at @s run function x_seat:menu
execute as @a[scores={x_SEAT_MENU=1..499}] at @s run scoreboard players reset @s x_SEAT_MENU
execute as @a[scores={x_SEAT_MENU=500}] at @s run tellraw @s "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
execute as @a[scores={x_SEAT_MENU=500}] at @s run scoreboard players reset @s x_SEAT_MENU