#######
# Compiled from data/x_seat/functions/uninstall.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/uninstall.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | uninstall
# Removes all traces of the S.E.A.T pack from world


execute if data storage x_core packs.x_seat run tellraw @a ["",{"text":"\n\nUninstalled Xmas Labs S.E.A.T Pack!\n\n","bold":true,"color":"gold"},{"text":"~ Finally taking a stand? ~\n\n\n","color":"light_purple","italic":true}]

function x_seat:disable
tag @e remove x_SEAT_PLAYER_DISABLED
tag @e remove x_SEAT_PLAYER_DISABLED_ADJUSTMENT
tag @e remove x_SEAT_PLAYER_DISABLED_ADJUSTMENT_LIMITS
tag @e remove x_SEAT_PLAYER_DISABLED_PROMPTS
tag @e remove x_SEAT_PLAYER_ENABLED_FORCE_SNEAKING
tag @e remove x_SEAT_DISABLED_PHYSICS
tag @e remove x_SEAT_ENABLED_ROTATION_LOCK
tag @e remove x_SEAT_ENABLED_FORCE_SIT_DOWN
tag @e remove x_SEAT_ENABLED_FORCE_SNEAKING
tag @e remove x_SEAT_ENABLED_FLOOR_BOUNCE
tag @e remove x_SEAT_DISABLED_FALL_DAMAGE
tag @e remove x_SEAT_DISABLED_ADJUSTMENT
tag @e remove x_SEAT_DISABLED_ON_MOBS
tag @e remove x_SEAT_DISABLED_ADJUSTMENT_LIMITS
tag @e remove x_SEAT_DISABLED_FREEZE_RIDE
tag @e remove x_SEAT_DISABLED_INVENTORY_BLOCK
tag @e remove x_SEAT_DISABLED_PROMPTS
data remove storage x_core flags.loadCPU__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadEIDs__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadTickRegister__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadSneakTimeRegisters__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadAttachmentRegisters__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadCollisionRegisters__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadScrollBarRegisters__Packs[{x_SEAT:1}]
data remove storage x_seat flags
data remove storage x_core packs.x_seat
scoreboard objectives remove x_SEAT_ID
scoreboard objectives remove x_SEAT_TICK
scoreboard objectives remove x_SEAT_SCROLLED
scoreboard objectives remove x_SEAT_MENU
scoreboard objectives remove S.E.A.T
tag @e remove x_SEAT_NS
advancement revoke @a from x_seat:pack_loaded