#######
# Compiled from data/x_seat/functions/uninstall.mcscript
# to .//Xmas Labs - S.E.A.T/data/x_seat/functions/uninstall.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# S.E.A.T | uninstall
# Removes all traces of the S.E.A.T pack from world


execute if data storage x_core packs.x_seat run tellraw @a ["",{"text":"\n\nUninstalled Xmas Labs S.E.A.T Pack!\n\n","bold":true,"color":"gold"},{"text":"~ Finally taking a stand? ~\n\n\n","color":"light_purple","italics":true}]

data remove storage x_core flags.loadCPU__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadEIDs__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadSneakTimeRegisters__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadAttachmentRegisters__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadCollisionRegisters__Packs[{x_SEAT:1}]
data remove storage x_core flags.loadScrollBarRegisters__Packs[{x_SEAT:1}]
data remove storage x_core flags.tpKill__Packs[{x_SEAT:1}]
data remove storage x_core flags.trackSneakTime__Packs[{x_SEAT:1}]
data remove storage x_core flags.scrollBar__Packs[{x_SEAT:1}]
data remove storage x_core flags.blockCollisions__Packs[{x_SEAT:1}]
data remove storage x_core flags.attach__Packs[{x_SEAT:1}]
data remove storage x_core flags.monitorItems__Packs[{x_SEAT:1}]
data remove storage x_seat flags
data remove storage x_core packs.x_seat
scoreboard objectives remove x_SEAT_ID
scoreboard objectives remove x_SEAT_TICK
scoreboard objectives remove x_SEAT_SCROLLED
scoreboard objectives remove x_SEAT_MENU
tag @e remove x_MAY_SIT
tag @e remove x_MAY_SIT_SKIP
tag @e remove x_MAY_NOT_SIT
tag @e remove x_MAY_ADJUST_SEAT
tag @e remove x_MAY_ADJUST_SEAT_SKIP
tag @e remove x_ADJUSTING_SEAT
tag @e remove x_ADJUSTING_SEAT_SKIP
tag @e remove x_SEATED
tag @e remove x_SEAT_BLOCKING_INTERACTIONS    
tag @e remove x_SEAT_BASE_PLAYER
tag @e remove x_SEAT_SURFACE_PLAYER
tag @e remove x_SEAT_ANCHOR_PLAYER
tag @e remove x_SEAT_RIDE
tag @e remove x_SEAT_NO_RIDE
tag @e remove x_SEAT_ANCHOR_RIDE
tag @e remove x_SEAT_ANCHOR_RIDE_FROZEN
execute as @e[tag=x_EID__SEAT] at @s run scoreboard players remove @s x_EID__T 1
execute as @e[tag=x_EID__SEAT] at @s run tag @s remove x_EID__SEAT
execute as @e[tag=x_NO_COLLIDE__SEAT] at @s run scoreboard players remove @s x_NO_COLLIDE__T 1
execute as @e[tag=x_NO_COLLIDE__SEAT] at @s run tag @s remove x_NO_COLLIDE__SEAT
execute as @e[tag=x_ATTACH__SEAT] at @s run scoreboard players remove @s x_ATTACH__T 1
execute as @e[tag=x_ATTACH__SEAT] at @s run tag @s remove x_ATTACH__SEAT
execute as @e[tag=x_SCROLLBAR__SEAT] at @s run scoreboard players remove @s x_SCROLLBAR__T 1
execute as @e[tag=x_SCROLLBAR__SEAT] at @s run tag @s remove x_SCROLLBAR__SEAT
tp @e[tag=x_SEAT_NS,tag=x_SEAT] ~ ~999 ~
kill @e[tag=x_SEAT_NS,tag=x_SEAT_SENSOR]
kill @e[tag=x_SEAT_NS,tag=x_SEAT_ANCHOR]
kill @e[tag=x_SEAT_NS,tag=x_SEAT_INTERACTION_BLOCKER]
kill @e[tag=x_SEAT_NS,tag=x_SEAT]
tag @e remove x_SEAT_NS
advancement revoke @a from x_seat:pack_loaded