#######
# Compiled from data/x_core/functions/__random_number.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/__random_number.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | __random_number
# Recursing part of random number function


scoreboard players operation x_RNG x_R0 = x_RNG x_R2
scoreboard players operation x_RNG x_R0 -= x_RNG x_R1
execute if score x_RNG x_R0 matches ..0 run scoreboard players set x_CPU x_R3 -1
execute if score x_RNG x_R0 matches ..0 run scoreboard players operation x_RNG x_R0 = x_RNG x_R1

execute unless score x_CPU x_R3 matches ..-1 run scoreboard players set x_CPU x_R0 2
execute unless score x_CPU x_R3 matches ..-1 run scoreboard players operation x_RNG x_R0 /= x_CPU x_R0
execute unless score x_CPU x_R3 matches ..-1 run scoreboard players operation x_RNG x_R0 += x_RNG x_R1
execute unless score x_CPU x_R3 matches ..-1 run scoreboard players set x_CPU x_R3 1
execute unless score x_CPU x_R3 matches ..-1 unless score x_RNG x_R3 matches 0.. run scoreboard players set x_RNG x_R3 50
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 10 if predicate x_core:random_10 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 20 if predicate x_core:random_20 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 30 if predicate x_core:random_30 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 40 if predicate x_core:random_40 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 50 if predicate x_core:random_50 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 60 if predicate x_core:random_60 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 70 if predicate x_core:random_70 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 80 if predicate x_core:random_80 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_RNG x_R3 matches 90 if predicate x_core:random_90 run scoreboard players set x_CPU x_R3 2
execute unless score x_CPU x_R3 matches ..-1 if score x_CPU x_R3 matches 1 run scoreboard players operation x_RNG x_R2 = x_RNG x_R0
execute unless score x_CPU x_R3 matches ..-1 unless score x_CPU x_R3 matches 1 run scoreboard players operation x_RNG x_R1 = x_RNG x_R0
execute unless score x_CPU x_R3 matches ..-1 run function x_core:__random_number

scoreboard players reset x_CPU x_R3