#######
# Compiled from data/x_core/functions/assign_eid.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/assign_eid.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | assign_eid
# Assign entity ID to calling entity.


execute store result score x_CPU x_EID run data get storage x_core shared.lastEID
scoreboard players add x_CPU x_EID 1
scoreboard players operation @s x_EID = x_CPU x_EID 
execute store result storage x_core shared.lastEID int 1 run scoreboard players get x_CPU x_EID