#######
# Compiled from data/x_core/functions/attach.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/attach.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | attach
# Attach(tp) entities tagged for attachment


execute unless score @s x_EID matches 1.. run function x_core:assign_eid

execute unless entity @s[type=minecraft:player] run tag @s add x_ATTACHING
execute if entity @s[type=minecraft:player] run summon minecraft:armor_stand ~ ~ ~ {Tags:[x_EID,x_ATTACHING,x_ATTACHING_ANCHOR],Invisible:1,Small:1,Marker:1}
execute if entity @s[type=minecraft:player] run scoreboard players operation @e[tag=x_ATTACHING_ANCHOR,limit=1,sort=nearest] x_PID = @s x_PID
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result score @e[tag=x_ATTACHING,limit=1] x_R0 run data get entity @s Pos[0] 1000000
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID run scoreboard players operation @e[tag=x_ATTACHING,limit=1] x_R0 += @e[tag=x_ATTACHING,limit=1] x_ATTACH_X
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result entity @e[tag=x_ATTACHING,limit=1] Pos[0] double 0.000001 run scoreboard players get @e[tag=x_ATTACHING,limit=1] x_R0 
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result score @e[tag=x_ATTACHING,limit=1] x_R0 run data get entity @s Pos[1] 1000000
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID run scoreboard players operation @e[tag=x_ATTACHING,limit=1] x_R0 += @e[tag=x_ATTACHING,limit=1] x_ATTACH_Y
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result entity @e[tag=x_ATTACHING,limit=1] Pos[1] double 0.000001 run scoreboard players get @e[tag=x_ATTACHING,limit=1] x_R0
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result score @e[tag=x_ATTACHING,limit=1] x_R0 run data get entity @s Pos[2] 1000000
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID run scoreboard players operation @e[tag=x_ATTACHING,limit=1] x_R0 += @e[tag=x_ATTACHING,limit=1] x_ATTACH_Z
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result entity @e[tag=x_ATTACHING,limit=1] Pos[2] double 0.000001 run scoreboard players get @e[tag=x_ATTACHING,limit=1] x_R0
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result score @e[tag=x_ATTACHING,tag=x_ATTACH_ROTATE,limit=1] x_R0 run data get entity @s Rotation[0] 10
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID run scoreboard players operation @e[tag=x_ATTACHING,tag=x_ATTACH_ROTATE,limit=1] x_R0 += @e[tag=x_ATTACHING,tag=x_ATTACH_ROTATE,limit=1] x_ATTACH_RY
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result entity @e[tag=x_ATTACHING,tag=x_ATTACH_ROTATE,limit=1] Rotation[0] float 0.1 run scoreboard players get @e[tag=x_ATTACHING,limit=1] x_R0 
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result score @e[tag=x_ATTACHING,tag=x_ATTACH_ROTATE,limit=1] x_R0 run data get entity @s Rotation[1] 10
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID run scoreboard players operation @e[tag=x_ATTACHING,tag=x_ATTACH_ROTATE,limit=1] x_R0 += @e[tag=x_ATTACHING,tag=x_ATTACH_ROTATE,limit=1] x_ATTACH_RX
execute as @e[tag=x_EID,tag=!x_TP_KILL] at @s if score @e[tag=x_ATTACHING,tag=!x_TP_KILL,limit=1] x_PID = @s x_EID store result entity @e[tag=x_ATTACHING,tag=x_ATTACH_ROTATE,limit=1] Rotation[1] float 0.1 run scoreboard players get @e[tag=x_ATTACHING,limit=1] x_R0 
execute rotated as @e[tag=x_ATTACHING_ANCHOR,limit=1,sort=nearest] run tp @s[type=minecraft:player] @e[tag=x_ATTACHING_ANCHOR,limit=1,sort=nearest]
kill @e[tag=x_ATTACHING_ANCHOR,limit=1,sort=nearest]
tag @s add x_ATTACH_SKIP
tag @s remove x_ATTACHING
execute as @e[scores={x_ATTACH__T=1..},tag=!x_ATTACH_SKIP,limit=1] at @s run function x_core:attach
execute unless entity @e[scores={x_ATTACH__T=1..},tag=!x_ATTACH_SKIP] run tag @e remove x_ATTACH_SKIP
