#######
# Compiled from data/x_core/functions/collision_blocking.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/collision_blocking.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | collision_blocking
# Collision blocking tasks.


execute as @e[scores={x_NO_COLLIDE__T=..0}] at @s run tag @s remove x_NO_COLLIDE
execute as @e[scores={x_NO_COLLIDE__T=..0}] at @s run team leave @s[team=x_NO_COLLIDE]
execute as @e[scores={x_NO_COLLIDE__T=..0}] at @s run scoreboard players reset @s x_NO_COLLIDE__T
execute as @e[tag=x_NO_COLLIDE] at @s unless entity @s[scores={x_NO_COLLIDE__T=0..}] run scoreboard players set @s x_NO_COLLIDE__T 1
execute as @e[scores={x_NO_COLLIDE__T=1..}] at @s run tag @s add x_NO_COLLIDE
execute as @e[scores={x_NO_COLLIDE__T=1..}] at @s run team join x_NO_COLLIDE @s
execute as @e[scores={x_COLLISION_B__T=..0}] at @s run tag @s remove x_DRAW_COLLISION_BARRIER
execute as @e[scores={x_COLLISION_B__T=..0}] at @s run scoreboard players reset @s x_COLLISION_B__T
execute as @e[tag=x_DRAW_COLLISION_BARRIER] at @s unless entity @s[scores={x_COLLISION_B__T=0..}] run scoreboard players set @s x_COLLISION_B__T 1
execute as @e[scores={x_COLLISION_B__T=1..}] at @s run tag @s add x_DRAW_COLLISION_BARRIER
execute as @e[scores={x_COLLISION_B__T=1..}] at @s unless entity @e[distance=..0.5,tag=x_COLLISION_BARRIER] run summon minecraft:falling_block ~ ~ ~ {Tags:[x_COLLISION_BARRIER,x_KILL_ON_UNINSTALL], Age:1, NoAI:1, BlockState:{Name:"minecraft:barrier"}}
execute as @e[tag=x_COLLISION_BARRIER] at @s run tp @s @e[distance=..1,tag=x_DRAW_COLLISION_BARRIER,limit=1,sort=nearest]
execute as @e[tag=x_COLLISION_BARRIER] at @s unless entity @e[distance=..0.5,tag=x_DRAW_COLLISION_HITBOX] run kill @s
execute as @a[scores={x_COLLISION_A__T=..0}] at @s run tag @s remove x_DRAW_COLLISION_ARMOR_STAND
execute as @a[scores={x_COLLISION_A__T=..0}] at @s run scoreboard players reset @s x_COLLISION_A__T
execute as @e[tag=x_DRAW_COLLISION_ARMOR_STAND] at @s unless entity @s[scores={x_COLLISION_A__T=0..}] run scoreboard players set @s x_COLLISION_A__T 1
execute as @e[scores={x_COLLISION_A__T=1..}] at @s run tag @s add x_DRAW_COLLISION_ARMOR_STAND
execute as @e[scores={x_COLLISION_A__T=1..}] at @s unless entity @e[distance=..0.5,tag=x_COLLISION_ARMOR_STAND] run summon minecraft:armor_stand ~ ~ ~ {Tags:[x_COLLISION_ARMOR_STAND,x_KILL_ON_UNINSTALL],Invisible:1,Invulnerable:1,Small:1}
execute as @e[tag=x_COLLISION_ARMOR_STAND] at @s run tp @s @p[distance=..1,tag=x_DRAW_COLLISION_ARMOR_STAND,limit=1,sort=nearest]
execute as @e[tag=x_COLLISION_ARMOR_STAND] at @s unless entity @e[distance=..0.5,tag=x_DRAW_COLLISION_ARMOR_STAND] run kill @s