#######
# Compiled from data/x_core/functions/get_random.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/get_random.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | get_random
# Generates a random number and stores it in the x_RNG player unit

