#######
# Compiled from data/x_core/functions/load_notify.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/load_notify.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | load_notify
# Loads notifications triggered by pack load


execute if data storage x_core flags{reload:0} run tellraw @a [{"text":"\n Merry Xmas!\n","bold":true,"color":"dark_green"},{"text":" Xmas Labs C.O.R.E Loaded! \n","italic":true,"color":"gold"}]

execute unless data storage x_core flags.reload run tellraw @a [{"text":"\n Merry Xmas!\n","bold":true,"color":"dark_green"},{"text":" Xmas Labs C.O.R.E Loaded! \n","italic":true,"color":"gold"}]

execute if data storage x_core flags{reload:-1} run tellraw @a [{"text":"\n Merry Xmas!\n","bold":true,"color":"dark_green"},{"text":" Xmas Labs C.O.R.E Re-Loaded! \n","italic":true,"color":"gold"}]
execute if data storage x_core flags{reload:-1} run data modify storage x_core flags.reload set value 0

data modify storage x_core flags merge value {loadNotified:1}