#######
# Compiled from data/x_core/functions/main.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/main.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | main
# Runs on every tick. About 20 times a second.


execute if data storage x_core packs{x_core:116505} run function x_core:runtime
execute unless data storage x_core packs{x_core:116505} run function x_core:uninstall
function x_core:test