#######
# Compiled from data/x_core/functions/manage_eids.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/manage_eids.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | manage_eids
# EID management tasks


execute as @e[scores={x_EID__T=..0}] at @s run tag @s remove x_EID
execute as @e[scores={x_EID__T=..0}] at @s run scoreboard players reset @s x_EID
execute as @e[scores={x_EID__T=..0}] at @s run scoreboard players reset @s x_EID__T
execute as @e[tag=x_EID] at @s unless entity @s[scores={x_EID__T=0..}] run scoreboard players set @s x_EID__T 1
execute as @e[scores={x_EID__T=1..}] at @s unless score @s x_EID matches 1.. run tag @s add x_EID
execute as @e[scores={x_EID__T=1..}] at @s unless score @s x_EID matches 1.. run function x_core:assign_eid
execute unless entity @e[scores={x_EID__T=1..}] run scoreboard players reset * x_EID
execute unless entity @e[scores={x_EID__T=1..}] run data modify storage x_core shared.lastEID set value 0
