#######
# Compiled from data/x_core/functions/monitor_items.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/monitor_items.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | monitor_items
# Performs item-specific tasks in entity inventories


clear @a #x_core:all{x_ITEM_TAGS:[x_CLEAR_FROM_INV]}
kill @e[type=minecraft:item,nbt={Item:{tag:{x_ITEM_TAGS:[x_KILL_ON_DROP]}}}]