#######
# Compiled from data/x_core/functions/random_number.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/random_number.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | random_number
# Generates a random number and stores it in the x_RNG player unit


execute if score x_RNG x_R1 > x_RNG x_R2 run scoreboard players operation x_CPU x_R0 = x_RNG x_R1
execute if score x_RNG x_R1 > x_RNG x_R2 run scoreboard players operation x_RNG x_R1 = x_RNG x_R2
execute if score x_RNG x_R1 > x_RNG x_R2 run scoreboard players operation x_RNG x_R2 = x_CPU x_R0

scoreboard players reset x_CPU x_R3
function x_core:__random_number