#######
# Compiled from data/x_core/functions/rotation_tracking.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/rotation_tracking.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | rotation_tracking
# Do rotation tracking tasks


execute as @e[scores={x_ROT_TRACK__T=..0}] at @s run tag @s remove x_TRACK_ROTATION
execute as @e[tag=x_TRACK_ROTATION] at @s unless entity @s[scores={x_ROT_TRACK__T=0..}] run scoreboard players set @s x_ROT_TRACK__T 1
execute as @e[scores={x_ROT_TRACK__T=1..}] at @s run tag @s add x_TRACK_ROTATION
execute as @e[scores={x_ROT_TRACK__T=1..}] at @s store result score @s x_ROT_Y run data get entity @s Rotation[0] 1
execute as @e[scores={x_ROT_TRACK__T=1..}] at @s store result score @s x_ROT_X run data get entity @s Rotation[X] 1