#######
# Compiled from data/x_core/functions/save_edata.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/save_edata.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | save_edata
# Save calling entity's data to storage.


tag @s add x_SAVE_EDATA
execute as @s[tag=x_SAVE_EDATA] at @s unless score @s x_EID matches 1.. run function x_core:assign_eid
execute as @s[tag=x_SAVE_EDATA] at @s store result score x_CPU x_EID run data get storage minecraft:x_core shared.entities[-1].eid 1
execute as @s[tag=x_SAVE_EDATA] at @s if score @s x_EID = x_CPU x_EID run data modify storage x_core shared.entities[-1].data set from entity @s
execute as @s[tag=x_SAVE_EDATA] at @s if score @s x_EID = x_CPU x_EID run tag @s add x_SAVED_EDATA
execute as @s[tag=x_SAVE_EDATA] at @s unless data storage x_core shared._entities run data modify storage x_core shared merge value {_entities:[]}
execute as @s[tag=x_SAVE_EDATA] at @s run data modify storage x_core shared._entities prepend from storage x_core shared.entities[-1]
execute as @s[tag=x_SAVE_EDATA] at @s run data remove storage x_core shared.entities[-1]
execute as @s[tag=x_SAVE_EDATA] at @s if data storage x_core shared.entities[0] run function x_core:save_edata
execute as @s[tag=x_SAVE_EDATA] at @s unless data storage x_core shared.entities[0] run tag @s[tag=!x_SAVED_EDATA] add x_UNSAVED_EDATA
execute as @s[tag=x_SAVE_EDATA] at @s unless data storage x_core shared.entities[0] run tag @s remove x_SAVED_EDATA 
execute as @s[tag=x_SAVE_EDATA] at @s unless data storage x_core shared.entities[0] run data modify storage x_core shared.entities set from storage x_core shared._entities
execute as @s[tag=x_SAVE_EDATA] at @s if entity @s[tag=x_UNSAVED_EDATA] run data modify storage x_core shared.entities append value {eid:0,data:{}}
execute as @s[tag=x_SAVE_EDATA] at @s if entity @s[tag=x_UNSAVED_EDATA] run data modify storage x_core shared.entities[-1].data set from entity @s
execute as @s[tag=x_SAVE_EDATA] at @s if entity @s[tag=x_UNSAVED_EDATA] store result storage x_core shared.entities[-1].eid int 1 run scoreboard players get @s x_EID
execute as @s[tag=x_SAVE_EDATA] at @s if entity @s[tag=x_UNSAVED_EDATA] run tag @s remove x_UNSAVED_EDATA
execute as @s[tag=x_SAVE_EDATA] at @s run data remove storage x_core shared._entities
execute as @s[tag=x_SAVE_EDATA] at @s run tag @s remove x_SAVE_EDATA