#######
# Compiled from data/x_core/functions/scrollbar.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/scrollbar.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | scrollbar
# Scrollbar tasks.


execute as @e[scores={x_SCROLLBAR__T=..0}] at @s run tag @s remove x_SCROLLBAR
execute as @e[tag=x_SCROLLBAR] at @s unless entity @s[scores={x_SCROLLBAR__T=0..}] run scoreboard players set @s x_SCROLLBAR__T 1
execute as @e[scores={x_SCROLLBAR__T=1..}] at @s run tag @s add x_SCROLLBAR
execute as @e[scores={x_SCROLLBAR__T=1..}] at @s store result score x_CPU x_SCROLL_POS run data get entity @s SelectedItemSlot 1
execute as @e[scores={x_SCROLLBAR__T=1..}] at @s if score x_CPU x_SCROLL_POS < @s x_SCROLL_POS run scoreboard players set @s x_SCROLL_DIR -1
execute as @e[scores={x_SCROLLBAR__T=1..}] at @s if score x_CPU x_SCROLL_POS = @s x_SCROLL_POS run scoreboard players set @s x_SCROLL_DIR 0
execute as @e[scores={x_SCROLLBAR__T=1..}] at @s if score x_CPU x_SCROLL_POS > @s x_SCROLL_POS run scoreboard players set @s x_SCROLL_DIR 1
execute as @e[scores={x_SCROLLBAR__T=1..}] at @s if score x_CPU x_SCROLL_POS matches ..1 if score @s x_SCROLL_POS matches 7.. run scoreboard players set @s x_SCROLL_DIR 1
execute as @e[scores={x_SCROLLBAR__T=1..}] at @s if score x_CPU x_SCROLL_POS matches 7.. if score @s x_SCROLL_POS matches ..1 run scoreboard players set @s x_SCROLL_DIR -1
execute as @e[scores={x_SCROLLBAR__T=1..}] at @s run scoreboard players operation @s x_SCROLL_POS = x_CPU x_SCROLL_POS