#######
# Compiled from data/x_core/functions/search.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/search.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | search
# Search entities using dynamic search values


tag @s add x_SEARCH 
tag @e remove x_FOUND 
execute as @e[tag=x_SEARCHABLE] at @s if score @s x_SEARCH_KEY = @e[tag=x_SEARCH,limit=1] x_SEARCH_KEY run tag @s add x_FOUND 
tag @s remove x_SEARCH 