#######
# Compiled from data/x_core/functions/sneak_time_tracking.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/sneak_time_tracking.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | sneak_time_tracking
# Sneak-time tracking tasks.


execute as @a[scores={x_SNEAK_TIME=1..}] at @s if score @s x_SNEAK_TIME = @s x__SNEAK_TIME run tag @s add x_SNEAK_RESET
execute as @a[scores={x_SNEAK_TIME=1..}] at @s run scoreboard players operation @s x__SNEAK_TIME = @s x_SNEAK_TIME
execute as @a[tag=x_SNEAK_RESET] at @s run scoreboard players set @s x__SNEAK_TIME 0
execute as @a[tag=x_SNEAK_RESET] at @s run scoreboard players set @s x_SNEAK_TIME 0
execute as @a[tag=x_SNEAK_RESET] at @s run tag @s remove x_SNEAK_RESET