#######
# Compiled from data/x_core/functions/test.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/test.mcfunction
#
# Generated by Minecraft Script for 1.16
######
scoreboard players set x_RNG x_R1 1
scoreboard players set x_RNG x_R2 100
function x_core:random_number