#######
# Compiled from data/x_core/functions/uninstall.mcscript
# to .//Xmas Labs - C.O.R.E/data/x_core/functions/uninstall.mcfunction
#
# Generated by Minecraft Script for 1.16
######


# C.O.R.E | uninstall
# Removes all traces of the C.O.R.E pack from world


execute if data storage x_core packs.x_core run tellraw @a ["",{"text":"\n\nUninstalled Xmas Labs C.O.R.E Pack ","bold":true,"color":"gold"},{"text":"\n(& packs that depend on it)!\n\n","color":"gold"},{"text":"~ It was fun while it lasted. ~\n\n\n","color":"light_purple","italics":true}]

scoreboard players reset x_CPU
scoreboard objectives remove x_R0
scoreboard objectives remove x_R1
scoreboard objectives remove x_R2
scoreboard objectives remove x_R3
scoreboard objectives remove x_EID__T
scoreboard objectives remove x_EID
scoreboard objectives remove x_PID
scoreboard objectives remove x_SEARCH_KEY
scoreboard objectives remove x_NO_COLLIDE__T
scoreboard objectives remove x_COLLISION_A__T
scoreboard objectives remove x_COLLISION_B__T
scoreboard objectives remove x_SNEAK_TIME
scoreboard objectives remove x__SNEAK_TIME
scoreboard objectives remove x_ATTACH__T
scoreboard objectives remove x_ATTACH_X
scoreboard objectives remove x_ATTACH_Y
scoreboard objectives remove x_ATTACH_Z
scoreboard objectives remove x_ATTACH_RX
scoreboard objectives remove x_ATTACH_RY
scoreboard objectives remove x_ROT_TRACK__T
scoreboard objectives remove x_ROT_X
scoreboard objectives remove x_ROT_Y
scoreboard objectives remove x_SCROLLBAR__T
scoreboard objectives remove x_SCROLL_POS
scoreboard objectives remove x_SCROLL_DIR
data remove storage x_core packs
data remove storage x_core flags
data remove storage x_core shared
tag @e remove x_EID
tag @e remove x_PID
tag @e remove x_NO_COLLIDE
tag @e remove x_DRAW_COLLISION_BARRIER
tag @e remove x_DRAW_COLLISION_ARMOR_STAND
tag @e remove x_ATTACH 
tag @e remove x_ATTACH_ROTATE
tag @e remove x_ATTACHING 
tag @e remove x_ATTACHED 
tag @e remove x_ATTACH_NEW_PRIMARY
tag @e remove x_ATTACH_NEW_SECONDARY
tag @e remove x_SEARCH 
tag @e remove x_SEARCHING 
tag @e remove x_FOUND 
tag @e remove x_SAVE_EDATA
tag @e remove x_SAVED_EDATA
tag @e remove x_LOAD_EDATA 
tag @e remove x_LOADED_EDATA
tag @e remove x_LOAD_INV 
tag @e[tag=x_KEEP] remove x_INV_LOADER 
tag @e[tag=x_KEEP] remove x_INV_ITEM 
tag @e[tag=x_KEEP] remove x_INV_ARMOR 
tag @e[tag=x_KEEP] remove x_INV_OFFHAND 
tag @e remove x_TRACK_ROTATION
tag @e remove x_CLEAR_ABTITLE
tag @e remove x_TP_KILL
tag @e remove x_SCROLLBAR
kill @e[tag=x_ATTACHING_ANCHOR]
kill @e[tag=x_COLLISION_ARMOR_STAND]
kill @e[tag=x_COLLISION_BARRIER]
kill @e[tag=x_INV_LOADER]
kill @e[tag=x_INV_ITEM]
kill @e[tag=x_INV_ARMOR]
kill @e[tag=x_INV_OFFHAND]
kill @e[tag=x_KILL_ON_UNINSTALL]
team remove x_NO_COLLIDE
advancement revoke @a from x_core:pack_loaded
advancement revoke @a from x_core:root_tab